/**
 * Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
 * Author: Andrew Stellman · Date: 2026-06-01 · Project: book-keeper-dashboard-v2
 *
 * Functional tests for AI Bookkeeper Chatbot.
 * Tests the SSE streaming, error handling, and state management layers.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

// ── SSE Parser Tests (chatApi.sendStream from client/src/lib/api.ts) ──

describe("chatApi.sendStream SSE parser", () => {
  function createMockStream(chunks: string[]): ReadableStream<Uint8Array> {
    const encoder = new TextEncoder();
    return new ReadableStream({
      async start(controller) {
        for (const chunk of chunks) {
          controller.enqueue(encoder.encode(chunk));
        }
        controller.close();
      },
    });
  }

  function createMockResponse(body: ReadableStream): Response {
    return { ok: true, body, headers: new Headers() } as Response;
  }

  it("should call onToken for each token event", async () => {
    const chunks = [`data: {"token":"BIR"}\n\ndata: {"token":" Form"}\n\n`];
    const res = createMockResponse(createMockStream(chunks));
    const onToken = vi.fn();
    const onDone = vi.fn();

    // We can't easily mock fetch at module level without a mock library,
    // so we test the parsing logic directly
    const reader = res.body!.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      for (const line of buffer.split("\n")) {
        if (line.startsWith("data: ")) {
          const data = JSON.parse(line.slice(6));
          if (data.token) onToken(data.token);
          if (data.usage) onDone();
        }
      }
    }

    expect(onToken).toHaveBeenCalledTimes(2);
    expect(onToken).toHaveBeenNthCalledWith(1, "BIR");
    expect(onToken).toHaveBeenNthCalledWith(2, " Form");
  });

  it("should call onDone on usage event", async () => {
    const chunks = [
      `data: {"token":"hello"}\n\ndata: {"usage": {"promptTokens":10,"completionTokens":5}}\n\n`,
    ];
    const res = createMockResponse(createMockStream(chunks));
    const onToken = vi.fn();
    const onDone = vi.fn();
    let finished = false;
    const finish = () => { if (!finished) { finished = true; onDone(); } };

    const reader = res.body!.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      for (const line of buffer.split("\n")) {
        if (line.startsWith("data: ")) {
          const data = JSON.parse(line.slice(6));
          if (data.token) onToken(data.token);
          if (data.usage) finish();
        }
      }
    }
    finish();

    expect(onDone).toHaveBeenCalledTimes(1);
  });

  it("should NOT call onDone twice (guard against double-fire)", async () => {
    // Simulate usage arriving in the data AND stream ending
    const chunks = [
      `data: {"usage": {"promptTokens":10,"completionTokens":5}}\n\n`,
    ];
    const res = createMockResponse(createMockStream(chunks));
    const onDone = vi.fn();
    let finished = false;
    const finish = () => { if (!finished) { finished = true; onDone(); } };

    const reader = res.body!.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      for (const line of buffer.split("\n")) {
        if (line.startsWith("data: ")) {
          const data = JSON.parse(line.slice(6));
          if (data.usage) finish();
        }
      }
    }
    finish(); // stream end also calls finish

    expect(onDone).toHaveBeenCalledTimes(1);
  });

  it("should handle error events from server", async () => {
    const chunks = [
      `data: {"error":"Rate limit exceeded"}\n\n`,
    ];
    const res = createMockResponse(createMockStream(chunks));
    const onError = vi.fn();

    const reader = res.body!.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        for (const line of buffer.split("\n")) {
          if (line.startsWith("data: ")) {
            const data = JSON.parse(line.slice(6));
            if (data.error) throw new Error(data.error);
          }
        }
      }
    } catch (err: any) {
      onError(err);
    }

    expect(onError).toHaveBeenCalledTimes(1);
    expect(onError.mock.calls[0][0].message).toBe("Rate limit exceeded");
  });

  it("should handle split SSE chunks across multiple reads", async () => {
    const chunks = [
      `data: {"tok`,
      `en":"hello"}\n\n`,
    ];
    const res = createMockResponse(createMockStream(chunks));
    const onToken = vi.fn();

    const reader = res.body!.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        if (line.startsWith("data: ")) {
          const data = JSON.parse(line.slice(6));
          if (data.token) onToken(data.token);
        }
      }
    }

    expect(onToken).toHaveBeenCalledWith("hello");
  });
});

// ── Zustand Chat Store Tests ──

describe("chat-store (Zustand)", () => {
  beforeEach(() => {
    // Reset store by re-importing would require module isolation
    // Instead, we test the store actions via direct import
    const { useChatStore } = require("../client/src/stores/chat-store");
    useChatStore.getState().clear();
  });

  it("should start with empty messages and closed panel", () => {
    const { useChatStore } = require("../client/src/stores/chat-store");
    const state = useChatStore.getState();
    expect(state.messages).toEqual([]);
    expect(state.isOpen).toBe(false);
    expect(state.isLoading).toBe(false);
    expect(state.error).toBeNull();
  });

  it("should toggle isOpen", () => {
    const { useChatStore } = require("../client/src/stores/chat-store");
    const store = useChatStore.getState();
    store.toggle();
    expect(useChatStore.getState().isOpen).toBe(true);
    useChatStore.getState().toggle();
    expect(useChatStore.getState().isOpen).toBe(false);
  });

  it("should add messages", () => {
    const { useChatStore } = require("../client/src/stores/chat-store");
    const msg = { id: "1", role: "user" as const, content: "hello", timestamp: 100 };
    useChatStore.getState().addMessage(msg);
    expect(useChatStore.getState().messages).toHaveLength(1);
    expect(useChatStore.getState().messages[0].content).toBe("hello");
  });

  it("should append tokens to the last assistant message", () => {
    const { useChatStore } = require("../client/src/stores/chat-store");
    useChatStore.getState().addMessage({ id: "1", role: "user", content: "hi", timestamp: 100 });
    useChatStore.getState().addMessage({ id: "2", role: "assistant", content: "", timestamp: 101 });
    useChatStore.getState().appendToken("BIR");
    useChatStore.getState().appendToken(" Form");
    const msgs = useChatStore.getState().messages;
    expect(msgs).toHaveLength(2);
    expect(msgs[1].content).toBe("BIR Form");
  });

  it("should clear all messages", () => {
    const { useChatStore } = require("../client/src/stores/chat-store");
    useChatStore.getState().addMessage({ id: "1", role: "user", content: "hi", timestamp: 100 });
    useChatStore.getState().setError("something broke");
    useChatStore.getState().clear();
    const state = useChatStore.getState();
    expect(state.messages).toEqual([]);
    expect(state.error).toBeNull();
  });

  it("should set error and stop loading", () => {
    const { useChatStore } = require("../client/src/stores/chat-store");
    useChatStore.getState().setLoading(true);
    useChatStore.getState().setError("API error");
    const state = useChatStore.getState();
    expect(state.error).toBe("API error");
    expect(state.isLoading).toBe(false);
  });
});

// ── MessageBubble Markdown Rendering Tests ──

describe("MessageBubble markdown rendering", () => {
  // Replicate the renderMarkdown logic from MessageBubble.tsx
  function escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }

  function renderMarkdown(text: string): string {
    return escapeHtml(text)
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/`([^`]+)`/g, "<code>$1</code>")
      .replace(/^\s*-\s+(.+)/gm, "<li>$1</li>")
      .replace(/(<li>[\s\S]*?<\/li>)(\s*<li>)/g, "$1$2")
      .replace(/(<li>[\s\S]*?<\/li>\s*)+/g, "<ul>$&</ul>")
      .replace(/\n/g, "<br/>");
  }

  it("should render bold text", () => {
    const result = renderMarkdown("**BIR Form** 2550M");
    expect(result).toContain("<strong>BIR Form</strong>");
  });

  it("should render inline code", () => {
    const result = renderMarkdown("Use `formCode` field");
    expect(result).toContain("<code>formCode</code>");
  });

  it("should escape HTML to prevent XSS", () => {
    const result = renderMarkdown("<script>alert('xss')</script>");
    expect(result).not.toContain("<script>");
    expect(result).toContain("&lt;script&gt;");
  });

  it("should render list items", () => {
    const result = renderMarkdown("- Item 1\n- Item 2");
    expect(result).toContain("<ul>");
    expect(result).toContain("<li>Item 1</li>");
    expect(result).toContain("<li>Item 2</li>");
  });

  it("should render newlines as <br/>", () => {
    const result = renderMarkdown("line1\nline2");
    expect(result).toBe("line1<br/>line2");
  });
});

// ── Prompt Builder Tests ──

describe("prompt-builder", () => {
  it("should build valid messages array with system prompt", async () => {
    // Dynamic import to test the actual module
    const { buildPrompt } = await import(
      "../server/src/lib/chat/prompt-builder.js"
    );
    const result = buildPrompt({
      userMessage: "What is 2550M?",
      history: [],
      forms: [
        {
          formCode: "2550M",
          name: "Monthly Withholding Tax",
          filingFrequency: "monthly",
          deadlineDay: 15,
          deadlineMonthOffset: 0,
          category: "withholding",
        },
      ],
      userRole: "bookkeeper",
    });

    expect(result).toHaveLength(2); // system + user
    expect(result[0].role).toBe("system");
    expect(result[0].content).toContain("BIR Form 2550M");
    expect(result[0].content).toContain("Monthly Withholding Tax");
    expect(result[0].content).toContain("bookkeeper");
    expect(result[1].role).toBe("user");
    expect(result[1].content).toBe("What is 2550M?");
  });

  it("should include history messages when provided", async () => {
    const { buildPrompt } = await import(
      "../server/src/lib/chat/prompt-builder.js"
    );
    const result = buildPrompt({
      userMessage: "Tell me more",
      history: [
        { role: "user", content: "What is 2550M?" },
        { role: "assistant", content: "BIR Form 2550M is..." },
      ],
      forms: [],
      userRole: "bookkeeper",
    });

    expect(result).toHaveLength(4); // system + history(2) + user
    expect(result[1].content).toBe("What is 2550M?");
    expect(result[2].content).toBe("BIR Form 2550M is...");
  });

  it("should show fallback message when no forms match", async () => {
    const { buildPrompt } = await import(
      "../server/src/lib/chat/prompt-builder.js"
    );
    const result = buildPrompt({
      userMessage: "What is XYZ?",
      history: [],
      forms: [],
      userRole: "admin",
    });

    expect(result[0].content).toContain("No matching forms found");
  });
});

// ── Form Retriever Query Tests ──

describe("form-retriever", () => {
  it("should build correct SQL LIKE term for form code query", async () => {
    const { findRelevantForms } = await import(
      "../server/src/lib/chat/form-retriever.js"
    );
    // The function queries the database which may not be available in test env.
    // We verify the function exists and has the right signature.
    expect(findRelevantForms).toBeDefined();
    expect(findRelevantForms.length).toBe(2); // query, limit
  });
});

// ── InputBar Component Tests ──

describe("InputBar behavior", () => {
  it("should not call onSend when disabled", () => {
    // Component logic test: InputBar has disabled prop
    // and should not call onSend when disabled=true
    const onSend = vi.fn();
    const disabled = true;
    // Simulate the handleSubmit logic from InputBar.tsx
    const input = "  test  ";
    const trimmed = input.trim();
    if (trimmed && !disabled) {
      onSend(trimmed);
    }
    expect(onSend).not.toHaveBeenCalled();
  });

  it("should trim whitespace before sending", () => {
    const onSend = vi.fn();
    const disabled = false;
    const input = "  hello  ";
    const trimmed = input.trim();
    if (trimmed && !disabled) {
      onSend(trimmed);
    }
    expect(onSend).toHaveBeenCalledWith("hello");
  });

  it("should not send empty messages", () => {
    const onSend = vi.fn();
    const disabled = false;
    const input = "   ";
    const trimmed = input.trim();
    if (trimmed && !disabled) {
      onSend(trimmed);
    }
    expect(onSend).not.toHaveBeenCalled();
  });
});

// ── SSE Responder Tests ──

describe("sse-responder", () => {
  it("should write correctly formatted SSE data", async () => {
    const { writeSSE } = await import(
      "../server/src/lib/chat/sse-responder.js"
    );
    const write = vi.fn();
    const res = { write } as any;
    writeSSE(res, { token: "hello" });
    expect(write).toHaveBeenCalledWith('data: {"token":"hello"}\n\n');
  });

  it("should write correctly formatted SSE error", async () => {
    const { writeSSEError } = await import(
      "../server/src/lib/chat/sse-responder.js"
    );
    const write = vi.fn();
    const res = { write } as any;
    writeSSEError(res, "Something broke");
    expect(write).toHaveBeenCalledWith('data: {"error":"Something broke"}\n\n');
  });
});
